### ISSUE TITLE
Issue to open in other languagens

### ISSUE THREAD

**Issue by Guicsr2** [BillyCurtis/OpenSpotifySafariExtension#2]
When I open the link through the safari and the spotify appmod will stop it does not recognize it, I think the problem is due to the fact that ru is using a language different from English to open the links, in this case the language that has a possible problem is Brazilian Portuguese
![IMG_0597](https://github.com/BillyCurtis/OpenSpotifySafariExtension/assets/169470593/f73a33c6-8bec-454f-a953-03a30f02b340)

**Comment by BillyCurtis** [comment]
Hi, Can you send me a link that you’re trying to open in Spotify? As when I change my language to Portuguese, it still opens the song inside Spotify for me.

**Comment by Guicsr2** [comment]
https://open.spotify.com/intl-pt/track/4nTrxp4aH0g2yLVPkFmljF?si=TxlXHoqPSR6TSlubbrsJ4A&nd=1&utm_medium=organic&_branch_referrer=H4sIAAAAAAAAA7WN3QqCMBzFn2Zeas3hRSAhxJDoQlKiu5jLj%2BXfbe0D9O2bQY8QHDhwfpxzRue0PSSJ1cqJfo2Z1jEIOSVHbdTTc5cr3ckIYdJ7gIc3kI9bBaUFwjRow%2FGvzdUcImcYn4IT2ZhFE1buBrxebtVEZ3hRlFIrUHpqFriX6l3V16ypwbetsWdSfJ8YQBsm%2Fv%2BGcCafge6jvmPOmy5XZmBS8A8ebTSnFwEAAA%3D%3D&product=open&%24full_url=https%3A%2F%2Fopen.spotify.com%2Ftrack%2F4nTrxp4aH0g2yLVPkFmljF%3Fsi%3DTxlXHoqPSR6TSlubbrsJ4A&feature=organic&_branch_match_id=1317565400570860633

**Comment by Guicsr2** [comment]
This link, but any song it seen the same menssage

**Comment by BillyCurtis** [comment]
That link seems to work for me

https://github.com/BillyCurtis/OpenSpotifySafariExtension/assets/38408756/b3b28e1d-ae0e-404d-bb3c-ddf2d8339028

**Comment by BillyCurtis** [comment]
I found out why it works for me it’s because I only changed the Spotify app language. when I changed my iPhone language Portuguese. I got the same error so I’ll have a look later

**Comment by Guicsr2** [comment]
Yes, the incompatibility problem must be linked to the ios language, it must modify the link and the app does not understand.

**Comment by BillyCurtis** [comment]
Can you try this to see if it fixes it for you? [OpenSpotifySafariExtension.appex.zip](https://github.com/BillyCurtis/OpenSpotifySafariExtension/files/15280238/OpenSpotifySafariExtension.appex.zip)

**Comment by Guicsr2** [comment]
Yes, of course, but I don't know how to install it like that, can you show it to me?

**Comment by BillyCurtis** [comment]
Check the [README ](https://github.com/BillyCurtis/OpenSpotifySafariExtension/blob/main/README.md) on how to install it

**Comment by Guicsr2** [comment]
![image](https://github.com/BillyCurtis/OpenSpotifySafariExtension/assets/169470593/27b148a8-f3eb-44bf-b93c-40cde6b5ec77)
 this part i dont understand, i need any app to find this directory?

**Comment by BillyCurtis** [comment]
No, just change the file extension from .ipa to .zip and extract it like a normal zip folder

**Comment by Guicsr2** [comment]
right!!

![IMG_25AFA528B989-1](https://github.com/BillyCurtis/OpenSpotifySafariExtension/assets/169470593/fe60aeba-9c15-46cf-b7b4-0e6596ecabdc)

there is not the folder write plugins

![IMG_25AFA528B989-2](https://github.com/BillyCurtis/OpenSpotifySafariExtension/assets/169470593/57696d47-29ca-4181-b2d1-c8810983c212)

**Comment by Guicsr2** [comment]
I got it, but i only access plugin folder in my mac, in ios i dont get it, but i put the new extension and it WORKS!!! Thank you!! What was the problem?

**Comment by BillyCurtis** [comment]
i had to remove the /intl-pt/ language codes from the url
