### ISSUE TITLE
Can you make one for twitter

### ISSUE THREAD

**Issue by JackPlaysGames0510** [BillyCurtis/OpenSpotifySafariExtension#7]

**Comment by BillyCurtis** [comment]
There already is one by [BandarHL](https://github.com/BandarHL/OpenTwitterSafariExtension)

**Comment by JackPlaysGames0510** [comment]
ever since it turns in to x.com it broke the extention

**Comment by BillyCurtis** [comment]
You just need to edit the manifest.json and add `*://*.x.com/*` to it

**Comment by JackPlaysGames0510** [comment]
oh ok will do that

**Comment by JackPlaysGames0510** [comment]
It work thanks
